### ISSUE TITLE
Update player url in SearchService

### ISSUE THREAD

**Issue by bugg86** [osu-tournament-rating/otr-api#218]
Update the url returned in `SearchPlayersByNameAsync` in `SearchService` to reflect changes made to the otr urls.
Currently the format of the url is `https://otr.stagec.xyz/users/{id}` with this service returning `/users/{id}`. The format of the url may change, so this issue was made to make sure we remember that this will have to be updated if/when the url changes.

**Comment by hburn7** [comment]
@bugg86 Could you write some more details? Not quite sure what all this encompasses.

**Comment by myssto** [comment]
So there is actually a much easier way to do this that is refactor-friendly. If you take a look at the way I implemented dynamic resource link generation in #223, you can obtain an `IUrlHelper` through the DI container which can parse out internal resource routes. If we couple the intended route of the resource to the DTO, this should be a pretty trivial change. I would say we can hold off on this until 223 is merged, because I can create something of a `ResourceRouteService` that can be used for both.
