### ISSUE TITLE
`<=` bug in leaderboard filters

### ISSUE THREAD

**Issue by hburn7** [osu-tournament-rating/otr-api#237]
This filter `https://otr.stagec.xyz/leaderboards?rating=100&rating=3150` excludes players with a rating equal to `3150`. Probably a simple `<=` bug in the leaderboard query. This also happens when filtering by matches played (on the upper bound). Does not appear to happen with rank checking.

**Comment by SourMongoose** [comment]
The real reason this bug exists is because worst hr player's actual rating is 3150.9XX, but is displayed on the leaderboards as 3150. You can confirm this by going to his profile and seeing that his rating is displayed "correctly" as 3151.

The leaderboard filter then maxes out at 3150, and thus the resulting range doesn't include his actual rating.
