### ISSUE TITLE
Modify `RatingAdjustment` object

### ISSUE THREAD

**Issue by hburn7** [osu-tournament-rating/otr-api#364]
- [x] The following fields need to be removed:
  - All `Percentile` fields
  - All `GlobalRank` fields
  - All `CountryRank` fields
  - `Rating` and `Volatility` delta fields (before and after are still required)
- [x] Create migrations
- [x] Convert `delta` fields to computed properties
- [x] Ensure computed `delta` fields are unmapped

**Comment by Pantex9** [comment]
Hi, i am interested in resolving this issue.

**Comment by myssto** [comment]
Because this essentially is removing the historical rank leaderboard functionality, we should discuss what we want to do about the things this will break. Namely the rank chart, highest global rank, and highest country rank.

Personally I think the rank chart can be axed all together, but I think we can at least mimic the way osu! stores your highest global rank with a timestamp. I'm just going to remove them all for now and we can talk about it at some point.

**Comment by hburn7** [comment]
Yeah remove all. Maybe they come back later.
